services:

  app:
    build:
      context: .          # ← Build context = root directory (bukan ./php)
      dockerfile: ./php/Dockerfile  # ← Path ke Dockerfile
    image: php:latest
    container_name: user-service
    hostname: "php"
    volumes:
      - .:/var/www/html 
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    networks:
      - microservices-db-dev
    env_file:
      - .env

  nginx_laravel:
    build: ./nginx
    image: nginx:latest
    container_name: nginx_laravel
    hostname: "nginx"
    ports:
      - "8450:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - microservices-db-dev

volumes:
  app-volumes:

networks:
  microservices-db-dev:  # Simplified network definition
    name: microservices_dev_microservices-db-dev
    external: true