services:
  app:
    build:
      context: .
      dockerfile: ./php/jenkins.Dockerfile
    image: php:latest
    container_name: user-service
    hostname: "php"
    ports: 
      - "9001:9001"
    # volumes:
    #   - ${PWD:-$(pwd)}:/var/www/html  # ✅ Use absolute path
    working_dir: /var/www/html
    networks:
      - nginx-user-service-network
      - microservices-db-dev
    env_file:
      - .env
    environment:
      - APP_ENV=development
      - APP_DEBUG=true

  nginx_laravel:
    build:
      context: .  # ← Root directory (consistent)
      dockerfile: ./nginx/jenkins.Dockerfile
    image: nginx:latest
    container_name: nginx-user-service
    hostname: "nginx"
    ports:
      - "8089:80"
    # volumes:
    #   - ${PWD:-$(pwd)}:/var/www/html  # ✅ Use absolute path
    depends_on:
      - app
    networks:
      - nginx-user-service-network
      - microservices-db-dev


networks:
  nginx-user-service-network:
    driver: bridge
  microservices-db-dev:  # Simplified network definition
    name: microservices_dev_microservices-db-dev
    external: true